export const botstats = [
  {
    type: "total",
    descriptions: [],
    rows: [
      {
        team: {
          name: "MAS de Fès",
          slug: "mas-de-fes",
          shortName: "MAS",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 13669,
          nameCode: "MDF",
          disabled: false,
          national: false,
          type: 0,
          id: 55035,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ffdf00",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "المغرب الفاسي",
              ru: "МАС Магхриб А Фес",
            },
            shortNameTranslation: {
              ar: "المغرب الفاسي",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Champions League",
          id: 804,
        },
        position: 1,
        matches: 6,
        wins: 3,
        scoresFor: 7,
        scoresAgainst: 2,
        id: 1729941,
        losses: 0,
        draws: 3,
        points: 12,
        scoreDiffFormatted: "+5",
      },
      {
        team: {
          name: "Raja Club Athletic",
          slug: "raja-club-athletic",
          shortName: "Raja CA",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 143317,
          nameCode: "RCA",
          disabled: false,
          national: false,
          type: 0,
          id: 41757,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#009966",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "الرجاء الرياضي",
              ru: "Раджа Касабланка",
            },
            shortNameTranslation: {
              ar: "الرجاء الرياضي",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Champions League",
          id: 804,
        },
        position: 2,
        matches: 5,
        wins: 3,
        scoresFor: 6,
        scoresAgainst: 1,
        id: 1729944,
        losses: 0,
        draws: 2,
        points: 11,
        scoreDiffFormatted: "+5",
      },
      {
        team: {
          name: "Wydad Casablanca",
          slug: "wydad-casablanca",
          shortName: "WAC",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 147660,
          nameCode: "WCA",
          disabled: false,
          national: false,
          type: 0,
          id: 36268,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ff0000",
            secondary: "#ff0000",
            text: "#ff0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي الوداد الرياضي",
              ru: "Видад АК",
            },
            shortNameTranslation: {
              ar: "الوداد الرياضي",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "CAF Confederation Cup",
          id: 25,
        },
        position: 3,
        matches: 4,
        wins: 3,
        scoresFor: 8,
        scoresAgainst: 3,
        id: 1729949,
        losses: 0,
        draws: 1,
        points: 10,
        scoreDiffFormatted: "+5",
      },
      {
        team: {
          name: "RS Berkane",
          slug: "rs-berkane",
          shortName: "RS Berkane",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 42786,
          nameCode: "RBE",
          disabled: false,
          national: false,
          type: 0,
          id: 80395,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#f95100",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي النهضة البركانية",
              ru: "Рсб Беркан",
            },
            shortNameTranslation: {
              ar: "النهضة البركانية",
            },
          },
        },
        descriptions: [],
        position: 4,
        matches: 4,
        wins: 2,
        scoresFor: 11,
        scoresAgainst: 6,
        id: 1729946,
        losses: 0,
        draws: 2,
        points: 8,
        scoreDiffFormatted: "+5",
      },
      {
        team: {
          name: "AS FAR Rabat",
          slug: "as-far-rabat",
          shortName: "AS FAR",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 55534,
          nameCode: "AFR",
          disabled: false,
          national: false,
          type: 0,
          id: 24394,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#000000",
            secondary: "#008040",
            text: "#008040",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي الجيش الملكي",
            },
            shortNameTranslation: {
              ar: "الجيش الملكي",
            },
          },
        },
        descriptions: [],
        position: 5,
        matches: 4,
        wins: 2,
        scoresFor: 6,
        scoresAgainst: 1,
        id: 1729934,
        losses: 0,
        draws: 2,
        points: 8,
        scoreDiffFormatted: "+5",
      },
      {
        team: {
          name: "CODM Meknès",
          slug: "codm-meknes",
          shortName: "CODM",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 9496,
          nameCode: "COD",
          national: false,
          type: 0,
          id: 55025,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ff0000",
            secondary: "#222226",
            text: "#222226",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "النادي المكناسي",
            },
            shortNameTranslation: {
              ar: "المكناسي",
            },
          },
        },
        descriptions: [],
        position: 6,
        matches: 5,
        wins: 2,
        scoresFor: 4,
        scoresAgainst: 3,
        id: 1729935,
        losses: 1,
        draws: 2,
        points: 8,
        scoreDiffFormatted: "+1",
      },
      {
        team: {
          name: "Olympique Dcheira",
          slug: "olympique-dcheira",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 2423,
          nameCode: "ODC",
          national: false,
          type: 0,
          id: 204299,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#009900",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "أولمبيك الدشيرة",
              hi: "ओल्य्म्पिके द्चेइरा",
            },
            shortNameTranslation: {
              ar: "أولمبيك الدشيرة",
            },
          },
        },
        descriptions: [],
        position: 7,
        matches: 6,
        wins: 2,
        scoresFor: 4,
        scoresAgainst: 8,
        id: 1729943,
        losses: 3,
        draws: 1,
        points: 7,
        scoreDiffFormatted: "-4",
      },
      {
        team: {
          name: "Olympic Safi",
          slug: "olympic-safi",
          shortName: "OC Safi",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 7692,
          nameCode: "OSA",
          national: false,
          type: 0,
          id: 55037,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#000040",
            secondary: "#ff0000",
            text: "#ff0000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "أولمبيك آسفي",
              ru: "Олимпик де Сафи",
            },
            shortNameTranslation: {
              ar: "أولمبيك آسفي",
            },
          },
        },
        descriptions: [],
        position: 8,
        matches: 4,
        wins: 1,
        scoresFor: 3,
        scoresAgainst: 5,
        id: 1729942,
        losses: 1,
        draws: 2,
        points: 5,
        scoreDiffFormatted: "-2",
      },
      {
        team: {
          name: "Union Touarga Sport",
          slug: "union-touarga-sport",
          shortName: "Union Touarga",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 3587,
          nameCode: "TOU",
          disabled: false,
          national: false,
          type: 0,
          id: 118834,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#fff000",
            secondary: "#009900",
            text: "#009900",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي الاتحاد التوركي",
            },
            shortNameTranslation: {
              ar: "الاتحاد التوركي",
            },
          },
        },
        descriptions: [],
        position: 9,
        matches: 6,
        wins: 0,
        scoresFor: 6,
        scoresAgainst: 7,
        id: 1729948,
        losses: 1,
        draws: 5,
        points: 5,
        scoreDiffFormatted: "-1",
      },
      {
        team: {
          name: "Ittihad Tanger",
          slug: "ittihad-tanger",
          shortName: "Ittihad Tanger",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 8753,
          nameCode: "ITA",
          disabled: false,
          national: false,
          type: 0,
          id: 87180,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#0000ff",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "إتحاد طنجة",
              ru: "Иттихад Танжер",
              hi: "इत्तिहाद टैनजर",
            },
            shortNameTranslation: {
              ar: "إتحاد طنجة",
            },
          },
        },
        descriptions: [],
        position: 10,
        matches: 6,
        wins: 0,
        scoresFor: 6,
        scoresAgainst: 9,
        id: 1729939,
        losses: 1,
        draws: 5,
        points: 5,
        scoreDiffFormatted: "-3",
      },
      {
        team: {
          name: "Renaissance Zemamra",
          slug: "renaissance-zemamra",
          shortName: "Renaissance Zemamra",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 3411,
          nameCode: "ZEM",
          national: false,
          type: 0,
          id: 263373,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ff5500",
            secondary: "#000000",
            text: "#000000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي نهضة الزمامرة",
              hi: "रेनैस्संस ज़ेमाम्रा",
            },
            shortNameTranslation: {
              ar: "نهضة الزمامرة",
            },
          },
        },
        descriptions: [],
        position: 11,
        matches: 5,
        wins: 1,
        scoresFor: 3,
        scoresAgainst: 6,
        id: 1729945,
        losses: 2,
        draws: 2,
        points: 5,
        scoreDiffFormatted: "-3",
      },
      {
        team: {
          name: "Fath Union Sport",
          slug: "fath-union-sport",
          shortName: "FUS Rabat",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 8072,
          nameCode: "FUS",
          disabled: false,
          national: false,
          type: 0,
          id: 55027,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ff0000",
            secondary: "#d90000",
            text: "#d90000",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي الفتح الرياضي",
              ru: "ФЮС Фат Юниан Спортив Рабат",
            },
            shortNameTranslation: {
              ar: "نادي الفتح الرياضي",
            },
          },
        },
        descriptions: [],
        position: 12,
        matches: 4,
        wins: 1,
        scoresFor: 4,
        scoresAgainst: 5,
        id: 1729937,
        losses: 2,
        draws: 1,
        points: 4,
        scoreDiffFormatted: "-1",
      },
      {
        team: {
          name: "Hassania d'Agadir",
          slug: "hassania-dagadir",
          shortName: "HUSA",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 7769,
          nameCode: "HDA",
          national: false,
          type: 0,
          id: 55039,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#e22028",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "حسنية أكادير",
            },
            shortNameTranslation: {
              ar: "حسنية أكادير",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Relegation Playoffs",
          id: 45,
        },
        position: 13,
        matches: 4,
        wins: 1,
        scoresFor: 3,
        scoresAgainst: 5,
        id: 1729938,
        losses: 2,
        draws: 1,
        points: 4,
        scoreDiffFormatted: "-2",
      },
      {
        team: {
          name: "Kawkab Athletic Club Marrakech",
          slug: "kawkab-athletic-club-marrakech",
          shortName: "KACM",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 11912,
          nameCode: "KAM",
          disabled: false,
          national: false,
          type: 0,
          id: 47696,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#ff0000",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي الكوكب الرياضي المراكشي",
            },
            shortNameTranslation: {
              ar: "الكوكب المراكشي",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Relegation Playoffs",
          id: 45,
        },
        position: 14,
        matches: 6,
        wins: 1,
        scoresFor: 5,
        scoresAgainst: 8,
        id: 1729940,
        losses: 4,
        draws: 1,
        points: 4,
        scoreDiffFormatted: "-3",
      },
      {
        team: {
          name: "Difaâ Hassani El-Jadidi",
          slug: "difaa-hassani-el-jadidi",
          shortName: "DHJ",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 4416,
          nameCode: "HAS",
          disabled: false,
          national: false,
          type: 0,
          id: 55043,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#287b50",
            secondary: "#ffffff",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "الدفاع الحسني الجديدي",
              ru: "Дифаа Хассани",
            },
            shortNameTranslation: {
              ar: "الدفاع الحسني الجديدي",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Relegation",
          id: 3,
        },
        position: 15,
        matches: 5,
        wins: 0,
        scoresFor: 3,
        scoresAgainst: 6,
        id: 1729936,
        losses: 2,
        draws: 3,
        points: 3,
        scoreDiffFormatted: "-3",
      },
      {
        team: {
          name: "Union Sportive Yacoub El Mansour",
          slug: "union-sportive-yacoub-el-mansour",
          shortName: "USYM",
          gender: "M",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          userCount: 1879,
          nameCode: "USY",
          disabled: false,
          national: false,
          type: 0,
          id: 479104,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          teamColors: {
            primary: "#374df5",
            secondary: "#374df5",
            text: "#ffffff",
          },
          fieldTranslations: {
            nameTranslation: {
              ar: "نادي اتحاد يعقوب المنصور",
            },
            shortNameTranslation: {
              ar: "اتحاد يعقوب المنصور",
            },
          },
        },
        descriptions: [],
        promotion: {
          text: "Relegation",
          id: 3,
        },
        position: 16,
        matches: 6,
        wins: 0,
        scoresFor: 6,
        scoresAgainst: 10,
        id: 1729947,
        losses: 3,
        draws: 3,
        points: 3,
        scoreDiffFormatted: "-4",
      },
    ],
    id: 186216,
    tournament: {
      name: "Botola Pro",
      slug: "botola",
      category: {
        name: "Morocco",
        slug: "morocco",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        id: 303,
        country: {
          alpha2: "MA",
          alpha3: "MAR",
          name: "Morocco",
          slug: "morocco",
        },
        flag: "morocco",
        alpha2: "MA",
        fieldTranslations: {
          nameTranslation: {
            ar: "المغرب",
          },
          shortNameTranslation: {},
        },
      },
      uniqueTournament: {
        name: "Botola Pro",
        slug: "botola-pro",
        primaryColorHex: "#03774c",
        secondaryColorHex: "#df180e",
        category: {
          name: "Morocco",
          slug: "morocco",
          sport: {
            name: "Football",
            slug: "football",
            id: 1,
          },
          id: 303,
          country: {
            alpha2: "MA",
            alpha3: "MAR",
            name: "Morocco",
            slug: "morocco",
          },
          flag: "morocco",
          alpha2: "MA",
          fieldTranslations: {
            nameTranslation: {
              ar: "المغرب",
            },
            shortNameTranslation: {},
          },
        },
        userCount: 22945,
        hasPerformanceGraphFeature: true,
        id: 937,
        country: {},
        displayInverseHomeAwayTeams: false,
        fieldTranslations: {
          nameTranslation: {
            ar: "البطولة الإحترافية 1",
            hi: "बोटोला प्रो",
            bn: "বোতোলা প্রো",
          },
          shortNameTranslation: {},
        },
      },
      priority: 0,
      isGroup: false,
      isLive: false,
      id: 3640,
      fieldTranslations: {
        nameTranslation: {
          ar: "الدوري المغربي لكرة القدم D1",
          hi: "बोटोला प्रो डी1",
          bn: "বোটোলা প্রো ডি1",
        },
        shortNameTranslation: {},
      },
    },
    name: "Botola Pro D1 25/26",
    updatedAtTimestamp: 1753043541,
  },
];

// https://www.sofascore.com/api/v1/unique-tournament/937/season/78750/statistics?limit=20&order=-rating&accumulation=total&group=summary
export const playerStatsData = {
  results: [
    {
      goals: 3,
      successfulDribbles: 3,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 90.63,
      rating: 8,
      player: {
        name: "Mohamed Rabie Hrimat",
        slug: "mohamed-rabie-hrimat",
        userCount: 1476,
        gender: "M",
        id: 919489,
        fieldTranslations: {
          nameTranslation: {
            ar: "محمد ربيع هريمات",
            hi: "मोहम्मद रबी ह्रीमत",
            bn: "মোহাম্মদ রাবি হ্রিমাট",
          },
          shortNameTranslation: {
            ar: "م. ر. هريمات",
            hi: "एम.आर. ह्रीमत",
            bn: "এম. আর. হ্রিমাট",
          },
        },
      },
      team: {
        name: "AS FAR Rabat",
        slug: "as-far-rabat",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 24394,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الجيش الملكي",
          },
          shortNameTranslation: {
            ar: "الجيش الملكي",
          },
        },
      },
    },
    {
      goals: 2,
      successfulDribbles: 24,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 77.84,
      rating: 8,
      player: {
        name: "Adam Ennafati",
        slug: "adam-ennafati",
        userCount: 634,
        gender: "M",
        id: 797021,
        fieldTranslations: {
          nameTranslation: {
            ar: "آدم النفاتي",
            hi: "एडम एन्नाफती",
            bn: "অ্যাডাম এননাফাতি",
          },
          shortNameTranslation: {
            ar: "آ. النفاتي",
            hi: "ए. एन्नाफती",
            bn: "এ. এননাফাতি",
          },
        },
      },
      team: {
        name: "Raja Club Athletic",
        slug: "raja-club-athletic",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 41757,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "الرجاء الرياضي",
            ru: "Раджа Касабланка",
          },
          shortNameTranslation: {
            ar: "الرجاء الرياضي",
          },
        },
      },
    },
    {
      goals: 3,
      successfulDribbles: 17,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 73.84,
      rating: 7.77,
      player: {
        name: "Ayoub Benaadi ",
        slug: "ayoub-benaadi",
        userCount: 37,
        gender: "M",
        id: 2161833,
        fieldTranslations: {
          nameTranslation: {
            ar: "أيوب بنعادي",
          },
          shortNameTranslation: {
            ar: "أ. بنعادي",
          },
        },
      },
      team: {
        name: "Olympique Dcheira",
        slug: "olympique-dcheira",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 204299,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "أولمبيك الدشيرة",
            hi: "ओल्य्म्पिके द्चेइरा",
          },
          shortNameTranslation: {
            ar: "أولمبيك الدشيرة",
          },
        },
      },
    },
    {
      goals: 1,
      successfulDribbles: 14,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 61.11,
      rating: 7.6,
      player: {
        name: "Youssef El Fahli",
        slug: "youssef-el-fahli",
        userCount: 138,
        gender: "M",
        id: 978955,
        fieldTranslations: {
          nameTranslation: {
            ar: "يوسف الفهلي",
          },
          shortNameTranslation: {
            ar: "ي. الفهلي",
          },
        },
      },
      team: {
        name: "AS FAR Rabat",
        slug: "as-far-rabat",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 24394,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الجيش الملكي",
          },
          shortNameTranslation: {
            ar: "الجيش الملكي",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 96.45,
      rating: 7.6,
      player: {
        name: "Mehdi Al Harrar",
        slug: "mehdi-harrar",
        userCount: 1734,
        gender: "M",
        id: 1140885,
        fieldTranslations: {
          nameTranslation: {
            ar: "مهدي الحارار",
          },
          shortNameTranslation: {
            ar: "م. الحارار",
          },
        },
      },
      team: {
        name: "Raja Club Athletic",
        slug: "raja-club-athletic",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 41757,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "الرجاء الرياضي",
            ru: "Раджа Касабланка",
          },
          shortNameTranslation: {
            ar: "الرجاء الرياضي",
          },
        },
      },
    },
    {
      goals: 3,
      successfulDribbles: 15,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 80.99,
      rating: 7.58,
      player: {
        name: "Mounir Chouiar",
        slug: "mounir-chouiar",
        userCount: 755,
        gender: "M",
        id: 845274,
        fieldTranslations: {
          nameTranslation: {
            ar: "منير شويعر",
            hi: "मुनीर चौइयार",
            bn: "মনির চৌয়ার",
          },
          shortNameTranslation: {
            ar: "م. شويعر",
            hi: "एम. चौइयार",
            bn: "এম. চৌয়ার",
          },
        },
      },
      team: {
        name: "RS Berkane",
        slug: "rs-berkane",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 80395,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي النهضة البركانية",
            ru: "Рсб Беркан",
          },
          shortNameTranslation: {
            ar: "النهضة البركانية",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 5,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 83.26,
      rating: 7.58,
      player: {
        name: "Anas Serrhat",
        slug: "anas-serrhat",
        userCount: 80,
        gender: "M",
        id: 1004248,
        fieldTranslations: {
          nameTranslation: {
            ar: "أنس سرحات",
          },
          shortNameTranslation: {
            ar: "أ. سرحات",
          },
        },
      },
      team: {
        name: "Fath Union Sport",
        slug: "fath-union-sport",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 55027,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الفتح الرياضي",
            ru: "ФЮС Фат Юниан Спортив Рабат",
          },
          shortNameTranslation: {
            ar: "نادي الفتح الرياضي",
          },
        },
      },
    },
    {
      goals: 1,
      successfulDribbles: 8,
      tackles: null,
      assists: 4,
      accuratePassesPercentage: 78.91,
      rating: 7.53,
      player: {
        name: "Mohamed Moufid",
        slug: "mohamed-moufid",
        userCount: 729,
        gender: "M",
        id: 1140872,
        fieldTranslations: {
          nameTranslation: {
            ar: "محمد مفيد",
          },
          shortNameTranslation: {
            ar: "م. مفيد",
          },
        },
      },
      team: {
        name: "Wydad Casablanca",
        slug: "wydad-casablanca",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 36268,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الوداد الرياضي",
            ru: "Видад АК",
          },
          shortNameTranslation: {
            ar: "الوداد الرياضي",
          },
        },
      },
    },
    {
      goals: 3,
      successfulDribbles: 3,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 73.91,
      rating: 7.5,
      player: {
        name: "Hamza Hannouri",
        slug: "hamza-hannouri",
        userCount: 376,
        gender: "M",
        id: 933770,
        fieldTranslations: {
          nameTranslation: {
            ar: "حمزة حنوري",
          },
          shortNameTranslation: {
            ar: "ح. حنوري",
          },
        },
      },
      team: {
        name: "Wydad Casablanca",
        slug: "wydad-casablanca",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 36268,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الوداد الرياضي",
            ru: "Видад АК",
          },
          shortNameTranslation: {
            ar: "الوداد الرياضي",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 2,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 0,
      rating: 7.5,
      player: {
        name: "Zakaria Ajoughlal",
        slug: "zakaria-ajoughlal",
        userCount: 65,
        gender: "M",
        id: 1894253,
        fieldTranslations: {
          nameTranslation: {
            ar: "زاكريا أجوغلال",
          },
          shortNameTranslation: {
            ar: "ز. أجوغلال",
          },
        },
      },
      team: {
        name: "AS FAR Rabat",
        slug: "as-far-rabat",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 24394,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الجيش الملكي",
          },
          shortNameTranslation: {
            ar: "الجيش الملكي",
          },
        },
      },
    },
    {
      goals: 4,
      successfulDribbles: 6,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 76.92,
      rating: 7.48,
      player: {
        name: "Oussama Lamlioui",
        slug: "oussama-lamlioui",
        userCount: 1903,
        gender: "M",
        id: 1140833,
        fieldTranslations: {
          nameTranslation: {
            ar: "أسامة لامليوي",
          },
          shortNameTranslation: {
            ar: "أ. لامليوي",
          },
        },
      },
      team: {
        name: "RS Berkane",
        slug: "rs-berkane",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 80395,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي النهضة البركانية",
            ru: "Рсб Беркан",
          },
          shortNameTranslation: {
            ar: "النهضة البركانية",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 12,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 79.82,
      rating: 7.4,
      player: {
        name: "Youssef Anouar",
        slug: "youssef-anouar",
        userCount: 50,
        gender: "M",
        id: 884821,
        fieldTranslations: {
          nameTranslation: {
            ar: "يوسف أنور",
          },
          shortNameTranslation: {
            ar: "ي. أنور",
          },
        },
      },
      team: {
        name: "CODM Meknès",
        slug: "codm-meknes",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 55025,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "النادي المكناسي",
          },
          shortNameTranslation: {
            ar: "المكناسي",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 78.38,
      rating: 7.38,
      player: {
        name: "Babacar Niasse",
        slug: "babacar-niasse",
        userCount: 497,
        gender: "M",
        id: 794543,
        fieldTranslations: {
          nameTranslation: {
            ar: "بابكر نياسي",
            hi: "बबाकार नियासे",
            bn: "বাবার নিয়াসে",
          },
          shortNameTranslation: {
            ar: "ب. نياسي",
            hi: "ए. पीपर",
            bn: "বি. নিয়াসে",
          },
        },
      },
      team: {
        name: "Difaâ Hassani El-Jadidi",
        slug: "difaa-hassani-el-jadidi",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 55043,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "الدفاع الحسني الجديدي",
            ru: "Дифаа Хассани",
          },
          shortNameTranslation: {
            ar: "الدفاع الحسني الجديدي",
          },
        },
      },
    },
    {
      goals: 2,
      successfulDribbles: 5,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 81.34,
      rating: 7.38,
      player: {
        name: "Youssef Mehri",
        slug: "youssef-mehri",
        userCount: 965,
        gender: "M",
        id: 1182584,
        fieldTranslations: {
          nameTranslation: {
            ar: "مهري، يوسف",
          },
          shortNameTranslation: {
            ar: "ي. مهري",
          },
        },
      },
      team: {
        name: "RS Berkane",
        slug: "rs-berkane",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 80395,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي النهضة البركانية",
            ru: "Рсб Беркан",
          },
          shortNameTranslation: {
            ar: "النهضة البركانية",
          },
        },
      },
    },
    {
      goals: 2,
      successfulDribbles: 16,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 64.81,
      rating: 7.36,
      player: {
        name: "Abdallah Ziani",
        slug: "abdallah-ziani",
        userCount: 19,
        gender: "M",
        id: 1874639,
        fieldTranslations: {
          nameTranslation: {
            ar: "عبد الله زياني",
          },
          shortNameTranslation: {
            ar: "ع. زياني",
          },
        },
      },
      team: {
        name: "Difaâ Hassani El-Jadidi",
        slug: "difaa-hassani-el-jadidi",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 55043,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "الدفاع الحسني الجديدي",
            ru: "Дифаа Хассани",
          },
          shortNameTranslation: {
            ar: "الدفاع الحسني الجديدي",
          },
        },
      },
    },
    {
      goals: 2,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 82.87,
      rating: 7.36,
      player: {
        name: "Mohamed Saoud",
        slug: "mohamed-saoud",
        userCount: 106,
        gender: "M",
        id: 359288,
        fieldTranslations: {
          nameTranslation: {
            ar: "محمد سعود",
          },
          shortNameTranslation: {
            ar: "م. سعود",
          },
        },
      },
      team: {
        name: "Ittihad Tanger",
        slug: "ittihad-tanger",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 87180,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "إتحاد طنجة",
            ru: "Иттихад Танжер",
            hi: "इत्तिहाद टैनजर",
          },
          shortNameTranslation: {
            ar: "إتحاد طنجة",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 89.47,
      rating: 7.35,
      player: {
        name: "Aymane Majid",
        slug: "aymane-majid",
        userCount: 37,
        gender: "M",
        id: 919469,
        fieldTranslations: {
          nameTranslation: {
            ar: "أيمن ماجد",
          },
          shortNameTranslation: {
            ar: "أ. ماجد",
          },
        },
      },
      team: {
        name: "CODM Meknès",
        slug: "codm-meknes",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 55025,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "النادي المكناسي",
          },
          shortNameTranslation: {
            ar: "المكناسي",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 80.36,
      rating: 7.33,
      player: {
        name: "Reda Ait Boughima",
        slug: "reda-ait-boughima",
        userCount: 17,
        gender: "M",
        id: 1468076,
        fieldTranslations: {
          nameTranslation: {
            ar: "رضا آيت بوغيمة",
          },
          shortNameTranslation: {
            ar: "ر. بوغيمة",
          },
        },
      },
      team: {
        name: "Renaissance Zemamra",
        slug: "renaissance-zemamra",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 263373,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي نهضة الزمامرة",
            hi: "रेनैस्संस ज़ेमाम्रा",
          },
          shortNameTranslation: {
            ar: "نهضة الزمامرة",
          },
        },
      },
    },
    {
      goals: 2,
      successfulDribbles: 3,
      tackles: null,
      assists: 1,
      accuratePassesPercentage: 78.57,
      rating: 7.33,
      player: {
        name: "Thembinkosi Lorch",
        slug: "thembinkosi-lorch",
        userCount: 3152,
        gender: "M",
        id: 894744,
        fieldTranslations: {
          nameTranslation: {
            ar: "ثيمبينكوسي لورش",
            hi: "थेम्बिन्कोसी लोर्च",
            bn: "থেমবিঙ্কোসি লর্চ",
          },
          shortNameTranslation: {
            ar: "ت. لورش",
            hi: "टी. लोर्च",
            bn: "টি. লর্চ",
          },
        },
      },
      team: {
        name: "Wydad Casablanca",
        slug: "wydad-casablanca",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 36268,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الوداد الرياضي",
            ru: "Видад АК",
          },
          shortNameTranslation: {
            ar: "الوداد الرياضي",
          },
        },
      },
    },
    {
      goals: 0,
      successfulDribbles: 0,
      tackles: null,
      assists: 0,
      accuratePassesPercentage: 91.26,
      rating: 7.33,
      player: {
        name: "El Mehdi Benabid",
        slug: "el-mehdi-benabid",
        userCount: 1674,
        gender: "M",
        id: 970630,
        fieldTranslations: {
          nameTranslation: {
            ar: "المهدي بنعبيد",
            hi: "एल मेहदी बेनाबिद",
            bn: "এল মেহেদী বেনাবিদ",
          },
          shortNameTranslation: {
            ar: "م. بنعبيد",
            hi: "ई.एम. बेनाबिद",
            bn: "ই. এম. বেনাবিদ",
          },
        },
      },
      team: {
        name: "Wydad Casablanca",
        slug: "wydad-casablanca",
        sport: {
          name: "Football",
          slug: "football",
          id: 1,
        },
        userCount: 0,
        national: false,
        type: 0,
        id: 36268,
        teamColors: {
          primary: "#374df5",
          secondary: "#374df5",
          text: "#ffffff",
        },
        fieldTranslations: {
          nameTranslation: {
            ar: "نادي الوداد الرياضي",
            ru: "Видад АК",
          },
          shortNameTranslation: {
            ar: "الوداد الرياضي",
          },
        },
      },
    },
  ],
  page: 1,
  pages: 19,
};
