export const info = {
  teams: [
    {
      name: "AS FAR Rabat",
      slug: "as-far-rabat",
      shortName: "AS FAR",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 55419,
      nameCode: "AFR",
      disabled: false,
      national: false,
      type: 0,
      id: 24394,
      teamColors: {
        primary: "#000000",
        secondary: "#008040",
        text: "#008040",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي الجيش الملكي",
        },
        shortNameTranslation: {
          ar: "الجيش الملكي",
        },
      },
    },
    {
      name: "CODM Meknès",
      slug: "codm-meknes",
      shortName: "CODM",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 9365,
      nameCode: "COD",
      national: false,
      type: 0,
      id: 55025,
      teamColors: {
        primary: "#ff0000",
        secondary: "#222226",
        text: "#222226",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "النادي المكناسي",
        },
        shortNameTranslation: {
          ar: "المكناسي",
        },
      },
    },
    {
      name: "Difaâ Hassani El-Jadidi",
      slug: "difaa-hassani-el-jadidi",
      shortName: "DHJ",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 4413,
      nameCode: "HAS",
      disabled: false,
      national: false,
      type: 0,
      id: 55043,
      teamColors: {
        primary: "#287b50",
        secondary: "#ffffff",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "الدفاع الحسني الجديدي",
          ru: "Дифаа Хассани",
        },
        shortNameTranslation: {
          ar: "الدفاع الحسني الجديدي",
        },
      },
    },
    {
      name: "Fath Union Sport",
      slug: "fath-union-sport",
      shortName: "FUS Rabat",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 8078,
      nameCode: "FUS",
      disabled: false,
      national: false,
      type: 0,
      id: 55027,
      teamColors: {
        primary: "#ff0000",
        secondary: "#d90000",
        text: "#d90000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي الفتح الرياضي",
          ru: "ФЮС Фат Юниан Спортив Рабат",
        },
        shortNameTranslation: {
          ar: "نادي الفتح الرياضي",
        },
      },
    },
    {
      name: "Hassania d'Agadir",
      slug: "hassania-dagadir",
      shortName: "HUSA",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 7774,
      nameCode: "HDA",
      national: false,
      type: 0,
      id: 55039,
      teamColors: {
        primary: "#e22028",
        secondary: "#ffffff",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "حسنية أكادير",
        },
        shortNameTranslation: {
          ar: "حسنية أكادير",
        },
      },
    },
    {
      name: "Ittihad Tanger",
      slug: "ittihad-tanger",
      shortName: "Ittihad Tanger",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 8759,
      nameCode: "ITA",
      disabled: false,
      national: false,
      type: 0,
      id: 87180,
      teamColors: {
        primary: "#0000ff",
        secondary: "#ffffff",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "إتحاد طنجة",
          ru: "Иттихад Танжер",
          hi: "इत्तिहाद टैनजर",
        },
        shortNameTranslation: {
          ar: "إتحاد طنجة",
        },
      },
    },
    {
      name: "Kawkab Athletic Club Marrakech",
      slug: "kawkab-athletic-club-marrakech",
      shortName: "KACM",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 11787,
      nameCode: "KAM",
      disabled: false,
      national: false,
      type: 0,
      id: 47696,
      teamColors: {
        primary: "#ff0000",
        secondary: "#ffffff",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي الكوكب الرياضي المراكشي",
        },
        shortNameTranslation: {
          ar: "الكوكب المراكشي",
        },
      },
    },
    {
      name: "MAS de Fès",
      slug: "mas-de-fes",
      shortName: "MAS",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 13670,
      nameCode: "MDF",
      disabled: false,
      national: false,
      type: 0,
      id: 55035,
      teamColors: {
        primary: "#ffdf00",
        secondary: "#000000",
        text: "#000000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "المغرب الفاسي",
          ru: "МАС Магхриб А Фес",
        },
        shortNameTranslation: {
          ar: "المغرب الفاسي",
        },
      },
    },
    {
      name: "Olympic Safi",
      slug: "olympic-safi",
      shortName: "OC Safi",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 7686,
      nameCode: "OSA",
      national: false,
      type: 0,
      id: 55037,
      teamColors: {
        primary: "#000040",
        secondary: "#ff0000",
        text: "#ff0000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "أولمبيك آسفي",
          ru: "Олимпик де Сафи",
        },
        shortNameTranslation: {
          ar: "أولمبيك آسفي",
        },
      },
    },
    {
      name: "Olympique Dcheira",
      slug: "olympique-dcheira",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 2426,
      nameCode: "ODC",
      national: false,
      type: 0,
      id: 204299,
      teamColors: {
        primary: "#009900",
        secondary: "#000000",
        text: "#000000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "أولمبيك الدشيرة",
          hi: "ओल्य्म्पिके द्चेइरा",
        },
        shortNameTranslation: {
          ar: "أولمبيك الدشيرة",
        },
      },
    },
    {
      name: "Raja Club Athletic",
      slug: "raja-club-athletic",
      shortName: "Raja CA",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 142933,
      nameCode: "RCA",
      disabled: false,
      national: false,
      type: 0,
      id: 41757,
      teamColors: {
        primary: "#009966",
        secondary: "#ffffff",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "الرجاء الرياضي",
          ru: "Раджа Касабланка",
        },
        shortNameTranslation: {
          ar: "الرجاء الرياضي",
        },
      },
    },
    {
      name: "Renaissance Zemamra",
      slug: "renaissance-zemamra",
      shortName: "Renaissance Zemamra",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 3419,
      nameCode: "ZEM",
      national: false,
      type: 0,
      id: 263373,
      teamColors: {
        primary: "#ff5500",
        secondary: "#000000",
        text: "#000000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي نهضة الزمامرة",
          hi: "रेनैस्संस ज़ेमाम्रा",
        },
        shortNameTranslation: {
          ar: "نهضة الزمامرة",
        },
      },
    },
    {
      name: "RS Berkane",
      slug: "rs-berkane",
      shortName: "RS Berkane",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 42563,
      nameCode: "RBE",
      disabled: false,
      national: false,
      type: 0,
      id: 80395,
      teamColors: {
        primary: "#f95100",
        secondary: "#000000",
        text: "#000000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي النهضة البركانية",
          ru: "Рсб Беркан",
        },
        shortNameTranslation: {
          ar: "النهضة البركانية",
        },
      },
    },
    {
      name: "Union Sportive Yacoub El Mansour",
      slug: "union-sportive-yacoub-el-mansour",
      shortName: "USYM",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 1841,
      nameCode: "USY",
      disabled: false,
      national: false,
      type: 0,
      id: 479104,
      teamColors: {
        primary: "#374df5",
        secondary: "#374df5",
        text: "#ffffff",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي اتحاد يعقوب المنصور",
        },
        shortNameTranslation: {
          ar: "اتحاد يعقوب المنصور",
        },
      },
    },
    {
      name: "Union Touarga Sport",
      slug: "union-touarga-sport",
      shortName: "Union Touarga",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 3542,
      nameCode: "TOU",
      disabled: false,
      national: false,
      type: 0,
      id: 118834,
      teamColors: {
        primary: "#fff000",
        secondary: "#009900",
        text: "#009900",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي الاتحاد التوركي",
        },
        shortNameTranslation: {
          ar: "الاتحاد التوركي",
        },
      },
    },
    {
      name: "Wydad Casablanca",
      slug: "wydad-casablanca",
      shortName: "WAC",
      gender: "M",
      sport: {
        name: "Football",
        slug: "football",
        id: 1,
      },
      userCount: 147227,
      nameCode: "WCA",
      disabled: false,
      national: false,
      type: 0,
      id: 36268,
      teamColors: {
        primary: "#ff0000",
        secondary: "#ff0000",
        text: "#ff0000",
      },
      fieldTranslations: {
        nameTranslation: {
          ar: "نادي الوداد الرياضي",
          ru: "Видад АК",
        },
        shortNameTranslation: {
          ar: "الوداد الرياضي",
        },
      },
    },
  ],
  statisticsGroups: {
    summary: [
      "goals",
      "successfulDribbles",
      "tackles",
      "assists",
      "accuratePassesPercentage",
      "rating",
    ],
    attack: [
      "goals",
      "bigChancesMissed",
      "successfulDribbles",
      "totalShots",
      "goalConversionPercentage",
      "rating",
    ],
    defence: [
      "tackles",
      "interceptions",
      "clearances",
      "errorLeadToGoal",
      "outfielderBlocks",
      "rating",
    ],
    passing: [
      "bigChancesCreated",
      "assists",
      "accuratePasses",
      "accuratePassesPercentage",
      "keyPasses",
      "rating",
    ],
    goalkeeper: [
      "saves",
      "cleanSheet",
      "penaltySave",
      "savedShotsFromInsideTheBox",
      "runsOut",
      "rating",
    ],
    detailed: {
      attack: [
        "goals",
        "bigChancesMissed",
        "successfulDribbles",
        "successfulDribblesPercentage",
        "totalShots",
        "shotsOnTarget",
        "shotsOffTarget",
        "blockedShots",
        "goalConversionPercentage",
        "penaltiesTaken",
        "penaltyGoals",
        "penaltyWon",
        "shotFromSetPiece",
        "freeKickGoal",
        "goalsFromInsideTheBox",
        "goalsFromOutsideTheBox",
        "headedGoals",
        "leftFootGoals",
        "rightFootGoals",
        "hitWoodwork",
        "offsides",
        "penaltyConversion",
        "setPieceConversion",
        "rating",
      ],
      defence: [
        "tackles",
        "interceptions",
        "penaltyConceded",
        "clearances",
        "errorLeadToGoal",
        "errorLeadToShot",
        "ownGoals",
        "dribbledPast",
        "cleanSheet",
        "outfielderBlocks",
        "rating",
      ],
      passing: [
        "bigChancesCreated",
        "assists",
        "accuratePasses",
        "inaccuratePasses",
        "totalPasses",
        "accuratePassesPercentage",
        "accurateOwnHalfPasses",
        "accurateOppositionHalfPasses",
        "accurateFinalThirdPasses",
        "keyPasses",
        "accurateCrosses",
        "accurateCrossesPercentage",
        "accurateLongBalls",
        "accurateLongBallsPercentage",
        "passToAssist",
        "rating",
      ],
      goalkeeper: [
        "saves",
        "cleanSheet",
        "penaltyFaced",
        "penaltySave",
        "savedShotsFromInsideTheBox",
        "savedShotsFromOutsideTheBox",
        "goalsConcededInsideTheBox",
        "goalsConcededOutsideTheBox",
        "punches",
        "runsOut",
        "successfulRunsOut",
        "highClaims",
        "crossesNotClaimed",
        "rating",
      ],
      other: [
        "yellowCards",
        "redCards",
        "groundDuelsWon",
        "groundDuelsWonPercentage",
        "aerialDuelsWon",
        "aerialDuelsWonPercentage",
        "totalDuelsWon",
        "totalDuelsWonPercentage",
        "minutesPlayed",
        "wasFouled",
        "fouls",
        "dispossessed",
        "possessionLost",
        "appearances",
        "matchesStarted",
        "rating",
      ],
    },
  },
  hideHomeAndAway: false,
  nationalities: {
    AO: "Angola",
    BE: "Belgium",
    BF: "Burkina Faso",
    BJ: "Benin",
    BR: "Brazil",
    BW: "Botswana",
    CD: "DR Congo",
    CG: "Congo Republic",
    CI: "Côte d'Ivoire",
    CM: "Cameroon",
    ES: "Spain",
    FR: "France",
    GP: "Guadeloupe",
    KE: "Kenya",
    MA: "Morocco",
    ML: "Mali",
    MR: "Mauritania",
    NG: "Nigeria",
    NL: "Netherlands",
    PT: "Portugal",
    RW: "Rwanda",
    SN: "Senegal",
    TG: "Togo",
    TN: "Tunisia",
    ZA: "South Africa",
  },
};
